@url = http://localhost:3000
###
# Test connection
POST {{url}}
Content-Type: application/json

{
  "type": "std:test-connection",
  "input": {},
  "config": {{config}}
}
###
# Discover schema
POST {{url}}
Content-Type: application/json

{
  "type": "std:account:discover-schema",
  "input": {},
  "config": {{config}}
}

HTTP/1.1 200  - OK
x-powered-by: Express
content-type: application/x-ndjson
date: Thu, 07 Nov 2024 11:08:54 GMT
connection: close
transfer-encoding: chunked
###
# Account list
POST {{url}}
Content-Type: application/json

{
  "type": "std:account:list",
  "input": {},
  "config": {{config}}
}
###
# Account read
POST {{url}}
Content-Type: application/json

{
  "type": "std:account:read",
  "input": {
    "identity": "3175644"
  },
  "config": {{config}}
}
###
# Entitlement list
POST {{url}}
Content-Type: application/json

{
  "type": "std:entitlement:list",
  "input": {
        "type": "group"
    },
  "config": {{config}}
}
###
# Entitlement read
POST {{url}}
Content-Type: application/json

{
  "type": "std:entitlement:read",
  "input": {
        "identity": "fc16aee3-0359-4d46-b746-b36459211660"
    },
  "config": {{config}}
}
###
# Account disable
POST {{url}}
Content-Type: application/json

{
  "type": "std:account:disable",
  "input": {
    "identity": "993",
    "key": { "simple": { "id": "993" } }
  },
"config": {{config}}
}
###
# Account enable
POST {{url}}
Content-Type: application/json

{
  "type": "std:account:enable",
  "input": {
    "identity": "993"
  },
  "config": {{config}}
}
###
# Account update
POST {{url}}
Content-Type: application/json

{
  "type": "std:account:update",
  "input": {"changes":[{"attribute":"groups","op":"Remove","value":"fc16aee3-0359-4d46-b746-b36459211660"}],"identity":"3175644","key":{"simple":{"id":"3175644"}}},
  "config": {{config}}
}
###
# Account create
POST {{url}}
Content-Type: application/json

{
  "type": "std:account:create",
  "input": {"attributes":{"groups":"fc16aee3-0359-4d46-b746-b36459211660","name":"amanda.ross"},"identity":null,"key":{"simple":{"id":null}}},
  "config": {{config}}
}