@url = http://localhost:3000
###
# Test connection
POST {{url}}
Content-Type: application/json

{
  "type": "std:test-connection",
  "input": {},
  "config": {{config}}
}
###
# Discover schema
POST {{url}}
Content-Type: application/json

{
  "type": "std:account:discover-schema",
  "input": {},
  "config": {{config}}
}

HTTP/1.1 200  - OK
x-powered-by: Express
content-type: application/x-ndjson
date: Thu, 07 Nov 2024 11:08:54 GMT
connection: close
transfer-encoding: chunked
###
# Account list
POST {{url}}
Content-Type: application/json

{
  "type": "std:account:list",
  "input": {},
  "config": {{config}}
}

HTTP/1.1 200  - OK
x-powered-by: Express
content-type: application/x-ndjson
date: Tue, 18 Feb 2025 15:52:12 GMT
connection: close
transfer-encoding: chunked
###
# Account read
POST {{url}}
Content-Type: application/json

{
  "type": "std:account:read",
  "input": {
    "identity": "b2bfbfef-e0bb-4624-98ca-04e3b8f56de0"
  },
  "config": {{config}}
}

HTTP/1.1 200  - OK
x-powered-by: Express
content-type: application/x-ndjson
date: Mon, 17 Feb 2025 16:36:57 GMT
connection: close
transfer-encoding: chunked
###
# Entitlement list
POST {{url}}
Content-Type: application/json

{
  "type": "std:entitlement:list",
  "input": {
        "type": "group"
    },
  "config": {{config}}
}
###
# Entitlement read
POST {{url}}
Content-Type: application/json

{
  "type": "std:entitlement:read",
  "input": {
        "identity": "fc16aee3-0359-4d46-b746-b36459211660"
    },
  "config": {{config}}
}
###
# Account disable
POST {{url}}
Content-Type: application/json

{
  "type": "std:account:disable",
  "input": {
    "identity": "993",
    "key": { "simple": { "id": "993" } }
  },
"config": {{config}}
}
###
# Account enable
POST {{url}}
Content-Type: application/json

{
  "type": "std:account:enable",
  "input": {
    "identity": "993"
  },
  "config": {{config}}
}
###
# Account update
POST {{url}}
Content-Type: application/json

{
  "type": "std:account:update",
  "input": {"changes":[{"attribute":"actions","op":"Add","value":["ee052a17b0e00474a9bb81b91f33cbcd1","774f900fcb0c4fe8b1238fe78ea231ce","421617998c384529885b950304f6364d"]}],"identity":"a57eedca-ecfa-4d66-8556-d979c053b633","key":{"simple":{"id":"3175644"}}},
  "config": {{config}}
}
###
# Account create
POST {{url}}
Content-Type: application/json

{
  "type": "std:account:create",
  "input": {"attributes":{"actions":["9fd9741e885e4564b4d0b3a35b6bda42","7eace9939f07c4a5cb9b4e859c5f0029c","ef3c614cb963443db9f33e0e31d8011d"],"uniqueID":"jake.maskell"}},
  "config": {{config}}
}

HTTP/1.1 200  - OK
x-powered-by: Express
content-type: application/x-ndjson
date: Tue, 18 Feb 2025 12:46:33 GMT
connection: close
transfer-encoding: chunked