@url = http://localhost:3000
###
# Test connection
POST {{url}}
Content-Type: application/json

{
  "type": "std:test-connection",
  "input": {},
  "config": {{config}}
}
###
# Discover schema
POST {{url}}
Content-Type: application/json

{
  "type": "std:account:discover-schema",
  "input": {},
  "config": {{config}}
}

HTTP/1.1 200  - OK
x-powered-by: Express
content-type: application/x-ndjson
date: Thu, 07 Nov 2024 11:08:54 GMT
connection: close
transfer-encoding: chunked
###
# Account list
POST {{url}}
Content-Type: application/json

{
  "type": "std:account:list",
  "input": {},
  "config": {{config}}
}

HTTP/1.1 200  - OK
x-powered-by: Express
content-type: application/x-ndjson
date: Mon, 17 Feb 2025 14:35:37 GMT
connection: close
transfer-encoding: chunked
###
# Account read
POST {{url}}
Content-Type: application/json

{
  "type": "std:account:read",
  "input": {
    "identity": "b2bfbfef-e0bb-4624-98ca-04e3b8f56de0"
  },
  "config": {{config}}
}

HTTP/1.1 200  - OK
x-powered-by: Express
content-type: application/x-ndjson
date: Mon, 17 Feb 2025 16:36:57 GMT
connection: close
transfer-encoding: chunked
###
# Entitlement list
POST {{url}}
Content-Type: application/json

{
  "type": "std:entitlement:list",
  "input": {
        "type": "group"
    },
  "config": {{config}}
}
###
# Entitlement read
POST {{url}}
Content-Type: application/json

{
  "type": "std:entitlement:read",
  "input": {
        "identity": "fc16aee3-0359-4d46-b746-b36459211660"
    },
  "config": {{config}}
}
###
# Account disable
POST {{url}}
Content-Type: application/json

{
  "type": "std:account:disable",
  "input": {
    "identity": "993",
    "key": { "simple": { "id": "993" } }
  },
"config": {{config}}
}
###
# Account enable
POST {{url}}
Content-Type: application/json

{
  "type": "std:account:enable",
  "input": {
    "identity": "993"
  },
  "config": {{config}}
}
###
# Account update
POST {{url}}
Content-Type: application/json

{
  "type": "std:account:update",
  "input": {"changes":[{"attribute":"actions","op":"Add","value":"report"}],"identity":"5cf22308-d9bb-4e95-acee-6be513aceb17","key":{"simple":{"id":"3175644"}}},
  "config": {{config}}
}

HTTP/1.1 200  - OK
x-powered-by: Express
content-type: application/x-ndjson
date: Thu, 13 Feb 2025 12:11:38 GMT
connection: close
transfer-encoding: chunked
###
# Account create
POST {{url}}
Content-Type: application/json

{
  "type": "std:account:create",
  "input": {"attributes":{"actions":["3b186995676f4eb28b8b7389365b12e9", "abdc85c46cdf4f42b559d812566b8bfb"],"uniqueID":"david.tyrrell"},"identity":null,"key":{"simple":{"id":null}}},
  "config": {{config}}
}

HTTP/1.1 200  - OK
x-powered-by: Express
content-type: application/x-ndjson
date: Tue, 04 Feb 2025 17:18:48 GMT
connection: close
transfer-encoding: chunked